version: '3.5'
services:
  node_server_replica_1:
    image: node:18-alpine
    environment:
      - PORT=4000
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - x_network
  node_server_replica_2:
    image: node:18-alpine
    environment:
      - PORT=5000
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - x_network
  node_server_replica_3:
    image: node:18-alpine
    environment:
      - PORT=6000
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - x_network
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 3500:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node_server_replica_1
      - node_server_replica_2
      - node_server_replica_3
    networks:
      - x_network
  
networks:
  x_network:
    driver: bridge
